# 1 master pod, 1 worker

# goal is to figure out how to get spark to run as master in the master pod and get spark to run as worker on worker pod and have them network together


### Definition for spark master and its service ###
apiVersion: v1
kind: Pod
metadata:
  name: spark-master
  labels:
    component: spark-master
spec:
  containers:
  - name: spark-master
    image: ghcr.io/ucsd-ets/spark-notebook:latest
    stdin: true
    tty: true
    ports:
    - containerPort: 7077
    - containerPort: 8080
    - containerPort: 4040
    - containerPort: 20002
    - containerPort: 50002
    - containerPort: 60002
    - containerPort: 60003
    - containerPort: 60004
---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
    - name: sparkui
      port: 4040
      targetPort: 4040
    - name: driverport
      port: 20002
      targetPort: 20002
    - name: blockmgrport
      port: 50002
      targetPort: 50002
    - name: fileserverport
      port: 60002
      targetPort: 60002
    - name: broadcastport
      port: 60003
      targetPort: 60003
    - name: replicaport
      port: 60004
      targetPort: 60004
  selector:
    component: spark-master
---
### Definition for spark worker and its service ###
apiVersion: v1
kind: Pod
metadata:
  name: spark-worker
  labels:
    component: spark-worker
spec:
  containers:
  - name: spark-worker
    image: ghcr.io/ucsd-ets/spark-notebook:latest
    stdin: true
    tty: true
    ports:
    - containerPort: 8081
    - containerPort: 30002
    - containerPort: 40002
    - containerPort: 50002
    - containerPort: 60002
    - containerPort: 60003
    - containerPort: 60004
---
kind: Service
apiVersion: v1
metadata:
  name: spark-worker
  labels:
    component: spark-worker
spec:
  ports:
    - name: webui
      port: 8081
      targetPort: 8081
    - name: workerport
      port: 30002
      targetPort: 30002
    - name: executorport
      port: 40002
      targetPort: 40002
    - name: blockmgr
      port: 50002
      targetPort: 50002
    - name: fileserverport
      port: 60002
      targetPort: 60002
    - name: broadcastport
      port: 60003
      targetPort: 60003
    - name: replicaport
      port: 60004
      targetPort: 60004
  selector:
    component: spark-worker