# # Service for spark workers
kind: Service
apiVersion: v1
metadata:
  name: spark-dev
  labels:
    # component: spark-dev
    run: spark-dev
spec:
  ports:
    - name: webui
      port: 8081
      targetPort: 8081
    - name: workerport
      port: 30002
      targetPort: 30002
    - name: executorport
      port: 40002
      targetPort: 40002
    - name: blockmgr
      port: 50002
      targetPort: 50002
    - name: fileserverport
      port: 60002
      targetPort: 60002
    - name: broadcastport
      port: 60003
      targetPort: 60003
    - name: replicaport
      port: 60004
      targetPort: 60004
  selector:
    run: spark-dev
---
### Definition for service ofs park jupyter worker ###
kind: Service
apiVersion: v1
metadata:
  name: spark-jupyter
  labels:
    # component: spark-dev
    app: spark-jupyter
spec:
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8082
      targetPort: 8082
    - name: workerport
      port: 30007
      targetPort: 30007
    - name: executorport
      port: 40007
      targetPort: 40007
    - name: blockmgr
      port: 50007
      targetPort: 50007
    - name: fileserverport
      port: 60007
      targetPort: 60007
    - name: broadcastport
      port: 60008
      targetPort: 60008
    - name: replicaport
      port: 60009
      targetPort: 60009
  selector:
    app: spark-jupyter