### Definition for service of master pod ###
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels: 
    run: spark-master
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
    - name: sparkui
      port: 4040
      targetPort: 4040
    - name: driverport
      port: 20002
      targetPort: 20002
    - name: blockmgrport
      port: 50002
      targetPort: 50002
    - name: fileserverport
      port: 60002
      targetPort: 60002
    - name: broadcastport
      port: 60003
      targetPort: 60003
    - name: replicaport
      port: 60004
      targetPort: 60004
  selector:
    run: spark-master
---
### Definition for spark worker and its service ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      run: spark-worker
  template:
    metadata:
      labels:
        run: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: ghcr.io/ucsd-ets/spark-notebook:latest
        command: ["/bin/sh","-c"]
        args: ["./spark-3.3.0-bin-hadoop3/sbin/start-worker.sh spark://spark-jupyter:7077; sleep inf"]
        resources:
          requests:
            memory: "32Gi"
            cpu: "2000m"
          limits:
            memory: "32Gi"
            cpu: "3000m"
        ports:
        - containerPort: 8081
        - containerPort: 30002
        - containerPort: 40002
        - containerPort: 50002
        - containerPort: 60002
        - containerPort: 60003
        - containerPort: 60004
---
kind: Service
apiVersion: v1
metadata:
  name: spark-worker
  labels:
    # component: spark-worker
    run: spark-worker
spec:
  ports:
    - name: webui
      port: 8081
      targetPort: 8081
    - name: workerport
      port: 30002
      targetPort: 30002
    - name: executorport
      port: 40002
      targetPort: 40002
    - name: blockmgr
      port: 50002
      targetPort: 50002
    - name: fileserverport
      port: 60002
      targetPort: 60002
    - name: broadcastport
      port: 60003
      targetPort: 60003
    - name: replicaport
      port: 60004
      targetPort: 60004
  selector:
    run: spark-worker
---
### Definition for service ofs park jupyter worker ###
kind: Service
apiVersion: v1
metadata:
  name: spark-jupyter
  labels:
    # component: spark-worker
    app: spark-jupyter
spec:
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8082
      targetPort: 8082
    - name: workerport
      port: 30007
      targetPort: 30007
    - name: executorport
      port: 40007
      targetPort: 40007
    - name: blockmgr
      port: 50007
      targetPort: 50007
    - name: fileserverport
      port: 60007
      targetPort: 60007
    - name: broadcastport
      port: 60008
      targetPort: 60008
    - name: replicaport
      port: 60009
      targetPort: 60009
  selector:
    app: spark-jupyter