### Definition for spark workers ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-dev
  labels:
    app: spark-dev
spec:
  replicas: {{ .Values.replicaCount | default 2}}
  selector:
    matchLabels:
      run: spark-dev
  template:
    metadata:
      labels:
        run: spark-dev
    spec:
      containers:
      - name: spark-dev
        image: ghcr.io/ucsd-ets/spark-notebook:latest
        command: ["/bin/sh","-c"]
        args: ["./spark-3.3.0-bin-hadoop3/sbin/start-worker.sh spark://spark-jupyter:7077; sleep inf"]
        resources:
          requests:
            memory: "32Gi"
            cpu: "2000m"
          limits:
            memory: "32Gi"
            cpu: "3000m"
        ports: 
        {{- range .Values.workers.ports}}
        - containerPort: {{.portNumber}}
        {{- end }} 

